services:
  - type: web
    name: build-level-backend
    runtime: node
    rootDir: buildlevel-backend
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD_HASH
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
